### PR TITLE
adding the bichon frise pictures

### PR DESCRIPTION
**Pull request by lxblvs**

### CODE REVIEW

**Comment by jigsawpieces** [comment]
@lxblvs we're in ❤️ with your bichon frise 😍😍😍
however I think he/she would be happier to live inside the folder with the other bichons: https://github.com/jigsawpieces/dog-api-images/tree/master/frise-bichon

can you move images in there and I'll merge your PR? thanks!!

**Comment by lxblvs** [comment]
Oooooh! There is already a directory! Will do :)

**Comment by lxblvs** [comment]
Isn't the breed officially called `bichon frise`?

**Comment by jigsawpieces** [comment]
yeh! but we have to name our folders in reverse order so that sub-breeds work, e.g. `hound/afghan`

**Pull request merged**
