### PR TITLE
Add "indian" folder and Indian dog breed images

### PR DESCRIPTION
**Pull request by amanr-dev**
Added indian dog breeds in new "indian" folder.

### CODE REVIEW

**Comment by amanr-dev** [comment]
Can you add this folder?

**Comment by amanr-dev** [comment]
Hi, can you check this.

**Comment by amanr-dev** [comment]
Hi @jigsawpieces , Please review the PR👍

**Comment by jigsawpieces** [comment]
Hi @amanr-dev unfortunately Indian is not an official dog breed - if these are Indian variants of existing dog breeds please you add these in separate folders, e.g. `/mastiff-indian/photo.jpg`

**Comment by amanr-dev** [comment]
> Hi @amanr-dev unfortunately Indian is not an official dog breed - if these are Indian variants of existing dog breeds please you add these in separate folders, e.g. `/mastiff-indian/photo.jpg`

ok

**Comment by amanr-dev** [comment]
Add breeds in  separate folders

**Comment by amanr-dev** [comment]
Hi @jigsawpieces please review the PR

**Comment by jigsawpieces** [comment]
Welcome to the pack 🐶

**Pull request merged**
