### PR TITLE
Folder maintenance

### PR DESCRIPTION
**Pull request by deeja**
- hyphen to split sub breeds
- underscore for whitespace 
- rename based on breed 
    - australian-shepherd -> shepherd-australian
    - bluetick -> coonhound-bluetick
    - frise-bichon → bichon_frise
    - dane-great → great_dane
    - Terrier-westhighland → terrier-west_highland
    - terrier-sealyham →terrier-sealy_ham
    - terrier-kerryblue →terrier-kerry_blue
    - stbernard →st_bernard
    - germanshepherd →shepherd-german
    - retriever-flatcoated →retriever-flat_coated
    - pointer-germanlonghair →pointer-german_long_hair
    - mexicanhairless → mexican_hairless
    - finnish-lapphund → lapphund-finnish
    - otterhound → hound-otter
    - cotondetulear → coton_de_tulear

### CODE REVIEW

**Comment by deeja** [comment]
I've updated some of the folders so I can use it with a test project. Thought it might be interesting to add back into the repo. No worries if not.

**Comment by jigsawpieces** [comment]
@ElliottLandsborough is this better formatting?

**Comment by ElliottLandsborough** [comment]
Yeah its a better way, but shouldn't be merged until I modify the api for the new format.

Will bring everything down otherwise!

**Comment by jigsawpieces** [comment]
> Yeah its a better way, but shouldn't be merged until I modify the api for the new format.
> 
> Will bring everything down otherwise!

That's what I thought... 😅

**Comment by deeja** [comment]
Great! Glad to be of help

**Pull request closed without merging**
